sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

install:
  - mvn clean install dockerfile:build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push alikian/sprintboot


cache:
  directories:
  - .autoconf
  - $HOME/.m2
